---
apiVersion: v1
kind: Service
metadata:
  name: consul-server-lb
spec:
  ports:
  - protocol: "TCP"
    port: 8501
    targetPort: 8501
  selector:
    app: consul
    component: server
  type: LoadBalancer
